### ISSUE TITLE
broken pechas (because of missing volumes?)

### ISSUE THREAD

**Issue by eroux** [OpenPecha/ocr-queue#6]
W1PD166109 / P005616 is not aligned at all (if you look at volume 12 for instance). I suspect it's because there are missing volumes at the beginning. The code should make sure that it records the volume number indicated in the original instead of assuming all volumes are there and in sequence

**Comment by eroux** [comment]
Another example:

in W4CZ45313 / P008105 all the volumes are off (because some are missing in the images)... but it's very strange: the meta.yml records the volumes but doesn't record the link between the volumes and the base layer files, I think it really should, otherwise this kind of situation becomes very ambiguous

for instance in the meta.yml instead of

```yaml
    9f608c17931543cda41e2c01e2c1ff49:
      image_group_id: I4CZ75258
      title: Volume 1 of bka' 'gyur/ (he mis bris ma/)
      volume_number: 1
      total_pages: 513
```

there should be

```yaml
    9f608c17931543cda41e2c01e2c1ff49:
      image_group_id: I4CZ75258
      title: Volume 1 of bka' 'gyur/ (he mis bris ma/)
      volume_number: 1
      total_pages: 513
      basefile: v001.txt
```
